engines:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,controversial,design"
  phpcodesniffer:
    enabled: true

ratings:
  paths:
    - src/**
    - "**.php"

exclude_paths:
  - vendor/**/*
  - .git/**/*
  - composer.*
